"""Zeta API エンドポイント表 (自動生成 — gen_endpoints.py で再生成)。

com.scatterlab.messenger 3.42.4 の index.android.bundle から抽出した 332 件。
手で編集しないこと。
"""

from __future__ import annotations

from typing import NamedTuple


class Endpoint(NamedTuple):
    """1 本の REST エンドポイント定義。"""

    name: str
    method: str
    path: str
    path_params: tuple[str, ...]
    response: str | None
    js_name: str


ENDPOINTS: dict[str, Endpoint] = {
    'attach_lorebook': Endpoint('attach_lorebook', 'PUT', '/v1/plots/:plotId/lorebooks/:lorebookId', ('plotId', 'lorebookId', ), None, 'attachLorebookApi'),
    'block_hashtag': Endpoint('block_hashtag', 'POST', '/v1/plots/hashtags/blocks', (), None, 'blockHashtagApi'),
    'block_plot': Endpoint('block_plot', 'POST', '/v1/plots/blocks', (), None, 'blockPlotApi'),
    'block_user': Endpoint('block_user', 'POST', '/v1/users/blocks', (), None, 'blockUserApi'),
    'cancel_toss_payments': Endpoint('cancel_toss_payments', 'POST', '/v1/toss-payments/cancellations', (), None, 'cancelTossPaymentsApi'),
    'cancel_zeta_pass': Endpoint('cancel_zeta_pass', 'POST', '/v1/zeta-pass/cancel', (), 'ZetaPassSubscriptionResponse', 'cancelZetaPassApi'),
    'change_zeta_pass_payment_method': Endpoint('change_zeta_pass_payment_method', 'PUT', '/v1/zeta-pass/payment-method', (), 'ZetaPassPaymentMethodResponse', 'changeZetaPassPaymentMethodApi'),
    'chat': Endpoint('chat', 'POST', '/v1/rooms/:roomId/messages/stream', ('roomId', ), None, 'chatApi'),
    'check_abusing_user_chat_profile': Endpoint('check_abusing_user_chat_profile', 'POST', '/v1/user-chat-profiles/abusing', (), 'CheckAbusingUserChatProfileResponse', 'checkAbusingUserChatProfileApi'),
    'check_feature_enabled': Endpoint('check_feature_enabled', 'GET', '/v1/feature-flags/:key', ('key', ), 'FeatureFlagResponse', 'checkFeatureEnabledApi'),
    'check_lorebook_contents': Endpoint('check_lorebook_contents', 'POST', '/v1/lorebooks/check-contents', (), None, 'checkLorebookContentsApi'),
    'check_lorebook_title': Endpoint('check_lorebook_title', 'GET', '/v1/lorebooks/check-title', (), 'CheckLorebookTitleResponse', 'checkLorebookTitleApi'),
    'check_plot_name': Endpoint('check_plot_name', 'GET', '/v1/plots/check-name', (), 'CheckPlotNameResponse', 'checkPlotNameApi'),
    'check_signup': Endpoint('check_signup', 'POST', '/v1/users/check', (), 'CheckSignupResponse', 'checkSignupApi'),
    'choose_option': Endpoint('choose_option', 'POST', '/v1/rooms/:roomId/options/:id', ('roomId', 'id', ), 'ChooseOptionResponse', 'chooseOptionApi'),
    'claim_reward_for_daily_quiz': Endpoint('claim_reward_for_daily_quiz', 'POST', '/v1/daily-quizzes/:quizId/claim-reward', ('quizId', ), None, 'claimRewardForDailyQuizApi'),
    'clear_zeta_pass_promotion_history': Endpoint('clear_zeta_pass_promotion_history', 'POST', '/debug/zeta-pass/promotion-history/clear', (), None, 'clearZetaPassPromotionHistoryApi'),
    'clone_room': Endpoint('clone_room', 'POST', '/v1/rooms/:roomId/clone', ('roomId', ), 'RoomApiDto', 'cloneRoomApi'),
    'confirm_toss_payments': Endpoint('confirm_toss_payments', 'POST', '/v1/toss-payments/confirmations', (), None, 'confirmTossPaymentsApi'),
    'confirm_zeta_pass_one_day_pass_web_payment': Endpoint('confirm_zeta_pass_one_day_pass_web_payment', 'POST', '/v1/zeta-pass/one-day-pass/purchase/web/confirmations', (), 'ZetaPassOneDayPassResponse', 'confirmZetaPassOneDayPassWebPaymentApi'),
    'confirm_zeta_pass_promotion_consent_via_brandpay': Endpoint('confirm_zeta_pass_promotion_consent_via_brandpay', 'POST', '/v1/zeta-pass/subscribe/promotion/brandpay/consent', (), 'ZetaPassSubscriptionResponse', 'confirmZetaPassPromotionConsentViaBrandpayApi'),
    'convert_zeta_pass_pro_subscription': Endpoint('convert_zeta_pass_pro_subscription', 'POST', '/v1/zeta-pass/pro-conversion/convert', (), 'ZetaPassProConversionStatusResponse', 'convertZetaPassProSubscriptionApi'),
    'count_message_bookmark_after': Endpoint('count_message_bookmark_after', 'GET', '/v1/rooms/:roomId/bookmarks/count', ('roomId', ), 'MessageBookmarkCountResponse', 'countMessageBookmarkAfterApi'),
    'count_plot_scrapped': Endpoint('count_plot_scrapped', 'GET', '/v1/plots/scrapped/count', (), 'CountPlotScrappedResponse', 'countPlotScrappedApi'),
    'create_and_select_user_plot_chat_profile': Endpoint('create_and_select_user_plot_chat_profile', 'POST', '/v1/rooms/:roomId/user-plot-chat-profiles/selected', ('roomId', ), None, 'createAndSelectUserPlotChatProfileApi'),
    'create_auto_payment_setting': Endpoint('create_auto_payment_setting', 'POST', '/v1/coin/auto-payment/settings', (), None, 'createAutoPaymentSettingApi'),
    'create_chat_message_report': Endpoint('create_chat_message_report', 'POST', '/v1/rooms/:roomId/messages/:messageId/reports', ('roomId', 'messageId', ), None, 'createChatMessageReportApi'),
    'create_chat_snapshot_image': Endpoint('create_chat_snapshot_image', 'POST', '/v1/rooms/:roomId/messages/:messageId/candidates/:candidateId/snapshot-images', ('roomId', 'messageId', 'candidateId', ), 'ChatSnapshotImageApiDto', 'createChatSnapshotImageApi'),
    'create_chat_snapshot_image_opinion': Endpoint('create_chat_snapshot_image_opinion', 'POST', '/v1/rooms/:roomId/messages/:messageId/candidates/:candidateId/snapshot-images/:snapshotImageId/opinion', ('roomId', 'messageId', 'candidateId', 'snapshotImageId', ), None, 'createChatSnapshotImageOpinionApi'),
    'create_lorebook': Endpoint('create_lorebook', 'POST', '/v1/lorebooks', (), 'LorebookApiDto', 'createLorebookApi'),
    'create_lorebook_report': Endpoint('create_lorebook_report', 'POST', '/v1/lorebooks/:lorebookId/reports', ('lorebookId', ), None, 'createLorebookReportApi'),
    'create_message_bookmark': Endpoint('create_message_bookmark', 'POST', '/v1/rooms/:roomId/bookmarks', ('roomId', ), 'MessageBookmarkApiDto', 'createMessageBookmarkApi'),
    'create_or_update_app_push_token': Endpoint('create_or_update_app_push_token', 'PUT', '/v1/app-push/tokens', (), None, 'createOrUpdateAppPushTokenApi'),
    'create_plot': Endpoint('create_plot', 'POST', '/v1/plots', (), 'PlotForCreatorApiDto', 'createPlotApi'),
    'create_plot_comment': Endpoint('create_plot_comment', 'POST', '/v1/plots/:plotId/comments', ('plotId', ), 'CreatePlotCommentResponse', 'createPlotCommentApi'),
    'create_plot_comment_reply': Endpoint('create_plot_comment_reply', 'POST', '/v1/plots/:plotId/comments/:commentId/replies', ('plotId', 'commentId', ), 'CreatePlotCommentResponse', 'createPlotCommentReplyApi'),
    'create_plot_report': Endpoint('create_plot_report', 'POST', '/v1/plots/:plotId/reports', ('plotId', ), None, 'createPlotReportApi'),
    'create_private_snapshot': Endpoint('create_private_snapshot', 'POST', '/v1/plots/:plotId/private-snapshots', ('plotId', ), 'PlotForCreatorApiDto', 'createPrivateSnapshotApi'),
    'create_room': Endpoint('create_room', 'POST', '/v1/rooms', (), 'RoomApiDto', 'createRoomApi'),
    'create_room_intro': Endpoint('create_room_intro', 'POST', '/v1/rooms/:roomId/intros', ('roomId', ), None, 'createRoomIntroApi'),
    'create_saved_room': Endpoint('create_saved_room', 'POST', '/v1/rooms/:roomId/save', ('roomId', ), 'RoomApiDto', 'createSavedRoomApi'),
    'create_user': Endpoint('create_user', 'POST', '/v1/users', (), 'SignUpResponse', 'createUserApi'),
    'create_user_chat_profile': Endpoint('create_user_chat_profile', 'POST', '/v1/user-chat-profiles', (), 'UserChatProfileApiDto', 'createUserChatProfileApi'),
    'create_withdrawal_report': Endpoint('create_withdrawal_report', 'POST', '/v1/withdrawal-requests', (), None, 'createWithdrawalReportApi'),
    'crop_plot_draft_character_profile_image': Endpoint('crop_plot_draft_character_profile_image', 'POST', '/v2/plots/:plotId/characters/:characterId/images/crop', ('plotId', 'characterId', ), 'CropImageResponse', 'cropPlotDraftCharacterProfileImageApi'),
    'crop_plot_draft_cover_image': Endpoint('crop_plot_draft_cover_image', 'POST', '/v2/plots/:plotId/images/crop', ('plotId', ), 'CropImageResponse', 'cropPlotDraftCoverImageApi'),
    'delete_app_push_token': Endpoint('delete_app_push_token', 'DELETE', '/v1/app-push/tokens', (), None, 'deleteAppPushTokenApi'),
    'delete_auto_payment_setting': Endpoint('delete_auto_payment_setting', 'DELETE', '/v1/coin/auto-payment/settings', (), None, 'deleteAutoPaymentSettingApi'),
    'delete_character_profile_image_generation_result': Endpoint('delete_character_profile_image_generation_result', 'DELETE', '/v1/plots/profile-image/result/:profileImageResultId', ('profileImageResultId', ), None, 'deleteCharacterProfileImageGenerationResultApi'),
    'delete_chat_snapshot_image': Endpoint('delete_chat_snapshot_image', 'DELETE', '/v1/rooms/:roomId/messages/:messageId/candidates/:candidateId/snapshot-images/:snapshotImageId', ('roomId', 'messageId', 'candidateId', 'snapshotImageId', ), None, 'deleteChatSnapshotImageApi'),
    'delete_draft_plot_character_profile_image': Endpoint('delete_draft_plot_character_profile_image', 'DELETE', '/v2/plots/:plotId/characters/:characterId/images', ('plotId', 'characterId', ), None, 'deleteDraftPlotCharacterProfileImageApi'),
    'delete_draft_plot_chat_profile_image': Endpoint('delete_draft_plot_chat_profile_image', 'DELETE', '/v2/plots/:plotId/chat-profiles/:chatProfileId/images', ('plotId', 'chatProfileId', ), None, 'deleteDraftPlotChatProfileImageApi'),
    'delete_lorebook': Endpoint('delete_lorebook', 'DELETE', '/v1/lorebooks/:id', ('id', ), None, 'deleteLorebookApi'),
    'delete_message_bookmark': Endpoint('delete_message_bookmark', 'DELETE', '/v1/rooms/:roomId/bookmarks/:bookmarkId', ('roomId', 'bookmarkId', ), None, 'deleteMessageBookmarkApi'),
    'delete_notification': Endpoint('delete_notification', 'DELETE', '/v1/notifications/:notificationId', ('notificationId', ), None, 'deleteNotificationApi'),
    'delete_plot_about_images': Endpoint('delete_plot_about_images', 'DELETE', '/v1/plots/:plotId/about-images', ('plotId', ), None, 'deletePlotAboutImagesApi'),
    'delete_plot_comment': Endpoint('delete_plot_comment', 'DELETE', '/v1/plots/:plotId/comments/:commentId', ('plotId', 'commentId', ), None, 'deletePlotCommentApi'),
    'delete_plot_comment_by_creator': Endpoint('delete_plot_comment_by_creator', 'DELETE', '/v1/creator/plots/:plotId/comments/:commentId', ('plotId', 'commentId', ), None, 'deletePlotCommentByCreatorApi'),
    'delete_plot_draft_cover_image': Endpoint('delete_plot_draft_cover_image', 'DELETE', '/v2/plots/:plotId/images', ('plotId', ), None, 'deletePlotDraftCoverImageApi'),
    'delete_plot_intro_images': Endpoint('delete_plot_intro_images', 'DELETE', '/v1/plots/:plotId/intro-images', ('plotId', ), None, 'deletePlotIntroImagesApi'),
    'delete_plot_profile_image_result_by_profile_image_result_id': Endpoint('delete_plot_profile_image_result_by_profile_image_result_id', 'DELETE', '/v1/plots/saved-profile-image/profile-image-result/:profileImageResultId', ('profileImageResultId', ), None, 'deletePlotProfileImageResultByProfileImageResultIdApi'),
    'delete_plot_profile_image_saved_results': Endpoint('delete_plot_profile_image_saved_results', 'DELETE', '/v1/plots/saved-profile-image', (), None, 'deletePlotProfileImageSavedResultsApi'),
    'delete_room': Endpoint('delete_room', 'DELETE', '/v1/rooms/:roomId', ('roomId', ), None, 'deleteRoomApi'),
    'delete_room_messages': Endpoint('delete_room_messages', 'DELETE', '/v1/rooms/:roomId/room-messages', ('roomId', ), 'DeleteMessageResponse', 'deleteRoomMessagesApi'),
    'delete_saved_room': Endpoint('delete_saved_room', 'DELETE', '/v1/rooms/:roomId/saved', ('roomId', ), None, 'deleteSavedRoomApi'),
    'delete_user_chat_profile': Endpoint('delete_user_chat_profile', 'DELETE', '/v1/user-chat-profiles/:id', ('id', ), None, 'deleteUserChatProfileApi'),
    'delete_user_profile_image': Endpoint('delete_user_profile_image', 'DELETE', '/v1/users/me/profile/images', (), None, 'deleteUserProfileImageApi'),
    'detach_lorebook': Endpoint('detach_lorebook', 'DELETE', '/v1/plots/:plotId/lorebooks/:lorebookId', ('plotId', 'lorebookId', ), None, 'detachLorebookApi'),
    'discover_popular_lorebooks': Endpoint('discover_popular_lorebooks', 'GET', '/v1/lorebooks/discovery/popular', (), 'LorebookDiscoveryResponse', 'discoverPopularLorebooksApi'),
    'discover_recent_play_lorebooks': Endpoint('discover_recent_play_lorebooks', 'GET', '/v1/lorebooks/discovery/recent-play', (), 'LorebookDiscoveryRecentPlayResponse', 'discoverRecentPlayLorebooksApi'),
    'discover_recommended_lorebooks': Endpoint('discover_recommended_lorebooks', 'GET', '/v1/lorebooks/discovery/recommend', (), 'LorebookDiscoveryResponse', 'discoverRecommendedLorebooksApi'),
    'enter_contest': Endpoint('enter_contest', 'PUT', '/v1/contest/plots/:plotId', ('plotId', ), None, 'enterContestApi'),
    'example_chat': Endpoint('example_chat', 'POST', '/v1/plots/:plotId/example-chat', ('plotId', ), None, 'exampleChatApi'),
    'expire_all_zeta_passes': Endpoint('expire_all_zeta_passes', 'POST', '/debug/zeta-pass/expire-all', (), None, 'expireAllZetaPassesApi'),
    'fetch_plot_recommended_messages': Endpoint('fetch_plot_recommended_messages', 'POST', '/v1/plots/:plotId/recommended-messages', ('plotId', ), 'RecommendedMessageResponse', 'fetchPlotRecommendedMessagesApi'),
    'follow_creator': Endpoint('follow_creator', 'POST', '/v1/creators/:creatorId/follow', ('creatorId', ), None, 'followCreatorApi'),
    'generate_creator_assistant_brief_backstories': Endpoint('generate_creator_assistant_brief_backstories', 'POST', '/v2/creator-assistant/generate-backstories', (), 'CreatorAssistantGenerateBackstoriesResponse', 'generateCreatorAssistantBriefBackstoriesApi'),
    'generate_creator_assistant_brief_characters': Endpoint('generate_creator_assistant_brief_characters', 'POST', '/v2/creator-assistant/generate-characters', (), 'CreatorAssistantGenerateCharactersResponse', 'generateCreatorAssistantBriefCharactersApi'),
    'generate_creator_assistant_brief_situations': Endpoint('generate_creator_assistant_brief_situations', 'POST', '/v2/creator-assistant/generate-situations', (), 'CreatorAssistantGenerateSituationsResponse', 'generateCreatorAssistantBriefSituationsApi'),
    'generate_creator_assistant_character_image_by_coin': Endpoint('generate_creator_assistant_character_image_by_coin', 'POST', '/v2/creator-assistant/generate-character-image/by-coin', (), 'CreatorAssistantGenerateCharacterImageResponse', 'generateCreatorAssistantCharacterImageByCoinApi'),
    'generate_creator_assistant_free_character_image': Endpoint('generate_creator_assistant_free_character_image', 'POST', '/v2/creator-assistant/generate-character-image', (), 'CreatorAssistantGenerateCharacterImageResponse', 'generateCreatorAssistantFreeCharacterImageApi'),
    'generate_sso_code': Endpoint('generate_sso_code', 'POST', '/v1/auth/sso/code', (), 'SsoCodeApiDto', 'generateSsoCodeApi'),
    'get_a_b_experiment': Endpoint('get_a_b_experiment', 'GET', '/v1/ab-experiments/:experimentId', ('experimentId', ), 'GetABExperimentResponse', 'getABExperimentApi'),
    'get_active_contest': Endpoint('get_active_contest', 'GET', '/v1/contest', (), 'ContestResponse', 'getActiveContestApi'),
    'get_active_room_id': Endpoint('get_active_room_id', 'GET', '/v1/rooms/active-room-id', (), 'GetRoomIdResponse', 'getActiveRoomIdApi'),
    'get_active_special_curation': Endpoint('get_active_special_curation', 'GET', '/v1/special-curation', (), 'SpecialCurationResponse', 'getActiveSpecialCurationApi'),
    'get_announcement': Endpoint('get_announcement', 'GET', '/v1/announcements/:id', ('id', ), 'AnnouncementApiDto', 'getAnnouncementApi'),
    'get_app_push_setting': Endpoint('get_app_push_setting', 'GET', '/v1/app-push/settings/:pushType', ('pushType', ), 'AppPushSettingApiDto', 'getAppPushSettingApi'),
    'get_app_push_settings': Endpoint('get_app_push_settings', 'GET', '/v1/app-push/settings', (), 'AppPushSettingsApiDto', 'getAppPushSettingsApi'),
    'get_auto_payment_setting_payment_method': Endpoint('get_auto_payment_setting_payment_method', 'GET', '/v1/coin/auto-payment/settings/payment-method', (), 'AutoPaymentPaymentMethodApiDto', 'getAutoPaymentSettingPaymentMethodApi'),
    'get_available_genres': Endpoint('get_available_genres', 'GET', '/v1/genres', (), 'AvailableGenresResponse', 'getAvailableGenresApi'),
    'get_awesome_username': Endpoint('get_awesome_username', 'GET', '/v1/usernames/awesome', (), 'UsernameResponse', 'getAwesomeUsernameApi'),
    'get_banner_announcement': Endpoint('get_banner_announcement', 'GET', '/v1/announcements/banner', (), 'GetBannerAnnouncementResponse', 'getBannerAnnouncementApi'),
    'get_banners': Endpoint('get_banners', 'GET', '/v1/banners', (), 'ListBannerResponse', 'getBannersApi'),
    'get_chat_model_by_debug': Endpoint('get_chat_model_by_debug', 'GET', '/debug/rooms/:roomId/candidates/:candidateId/model', ('roomId', 'candidateId', ), 'GetChatModelByDebugResponse', 'getChatModelByDebugApi'),
    'get_chat_snapshot_image': Endpoint('get_chat_snapshot_image', 'GET', '/v1/rooms/:roomId/messages/:messageId/candidates/:candidateId/snapshot-images/:snapshotImageId', ('roomId', 'messageId', 'candidateId', 'snapshotImageId', ), 'ChatSnapshotImageApiDto', 'getChatSnapshotImageApi'),
    'get_coin_balance': Endpoint('get_coin_balance', 'GET', '/v1/coin/balance', (), 'CoinBalanceResponse', 'getCoinBalanceApi'),
    'get_coin_deposit_detail': Endpoint('get_coin_deposit_detail', 'GET', '/v1/coin/deposits/:transactionId', ('transactionId', ), 'CoinDepositDetailResponse', 'getCoinDepositDetailApi'),
    'get_connected_external_platforms': Endpoint('get_connected_external_platforms', 'GET', '/v1/auth/connected-external-platforms', (), 'GetConnectedExternalPlatformsResponse', 'getConnectedExternalPlatformsApi'),
    'get_creator_assistant_brief_quota': Endpoint('get_creator_assistant_brief_quota', 'GET', '/v2/creator-assistant/quota', (), 'CreatorAssistantBriefQuotaResponse', 'getCreatorAssistantBriefQuotaApi'),
    'get_creator_assistant_brief_vibes': Endpoint('get_creator_assistant_brief_vibes', 'GET', '/v2/creator-assistant/vibes', (), 'CreatorAssistantVibesResponse', 'getCreatorAssistantBriefVibesApi'),
    'get_creator_assistant_styles': Endpoint('get_creator_assistant_styles', 'GET', '/v2/creator-assistant/styles', (), 'CreatorAssistantStylesResponse', 'getCreatorAssistantStylesApi'),
    'get_creator_dashboard_summary': Endpoint('get_creator_dashboard_summary', 'GET', '/v1/creators/dashboard/summary', (), 'CreatorDashboardSummaryApiDto', 'getCreatorDashboardSummaryApi'),
    'get_creator_follow': Endpoint('get_creator_follow', 'GET', '/v1/creators/:creatorId/follow', ('creatorId', ), 'GetCreatorFollowResponse', 'getCreatorFollowApi'),
    'get_creator_plot': Endpoint('get_creator_plot', 'GET', '/v1/plots/:plotId/creator', ('plotId', ), 'PlotForCreatorApiDto', 'getCreatorPlotApi'),
    'get_creator_stats': Endpoint('get_creator_stats', 'GET', '/v1/creators/:creatorId/stats', ('creatorId', ), 'CreatorStatsApiDto', 'getCreatorStatsApi'),
    'get_cyoa_setting': Endpoint('get_cyoa_setting', 'GET', '/v1/rooms/:roomId/settings/cyoa', ('roomId', ), 'RoomCyoaSettingApiDto', 'getCyoaSettingApi'),
    'get_daily_quiz_enabled': Endpoint('get_daily_quiz_enabled', 'GET', '/v1/daily-quizzes/enabled', (), 'DailyQuizEnabledResponse', 'getDailyQuizEnabledApi'),
    'get_daily_quiz_winners': Endpoint('get_daily_quiz_winners', 'GET', '/v1/daily-quizzes/winners', (), 'DailyQuizWinnersResponse', 'getDailyQuizWinnersApi'),
    'get_daily_reward_amount': Endpoint('get_daily_reward_amount', 'GET', '/v1/coin/daily-rewards/amount', (), 'CoinDailyRewardAmountResponse', 'getDailyRewardAmountApi'),
    'get_daily_reward_left': Endpoint('get_daily_reward_left', 'GET', '/v1/coin/daily-rewards/left-attempts', (), 'CoinDailyRewardLeftResponse', 'getDailyRewardLeftApi'),
    'get_following_creator_count': Endpoint('get_following_creator_count', 'GET', '/v1/creators/me/followings/count', (), 'GetFollowingCreatorCountResponse', 'getFollowingCreatorCountApi'),
    'get_home_layout_section': Endpoint('get_home_layout_section', 'GET', '/v1/layout-sections/home', (), 'GetHomeLayoutSectionResponse', 'getHomeLayoutSectionApi'),
    'get_infinite_plots': Endpoint('get_infinite_plots', 'GET', '/v1/infinite-plots', (), 'InfinitePlotsResponse', 'getInfinitePlotsApi'),
    'get_info_box_setting': Endpoint('get_info_box_setting', 'GET', '/v1/rooms/:roomId/settings/info-box', ('roomId', ), 'RoomInfoBoxSettingApiDto', 'getInfoBoxSettingApi'),
    'get_latest_creator_plot_comment': Endpoint('get_latest_creator_plot_comment', 'GET', '/v1/creator/comments/latest', (), 'LatestCreatorCommentResponse', 'getLatestCreatorPlotCommentApi'),
    'get_latest_notification_updated_at': Endpoint('get_latest_notification_updated_at', 'GET', '/v1/notifications/latest-updated-at', (), 'GetLatestNotificationUpdatedAtResponse', 'getLatestNotificationUpdatedAtApi'),
    'get_lorebook': Endpoint('get_lorebook', 'GET', '/v1/lorebooks/:id', ('id', ), 'LorebookApiDto', 'getLorebookApi'),
    'get_lorebook_connected_plot_stats': Endpoint('get_lorebook_connected_plot_stats', 'GET', '/v1/lorebooks/:lorebookId/plot-stats', ('lorebookId', ), 'LorebookAttachedPlotsResponse', 'getLorebookConnectedPlotStatsApi'),
    'get_main_layout': Endpoint('get_main_layout', 'GET', '/v1/layouts/main', (), 'GetLayoutResponse', 'getMainLayoutApi'),
    'get_message_bookmark_usage': Endpoint('get_message_bookmark_usage', 'GET', '/v1/rooms/:roomId/bookmarks/usage', ('roomId', ), 'MessageBookmarkUsageResponse', 'getMessageBookmarkUsageApi'),
    'get_message_metadata_by_debug': Endpoint('get_message_metadata_by_debug', 'GET', '/debug/rooms/:roomId/messages/:messageId/metadata', ('roomId', 'messageId', ), 'GetChatMessageMetadataByDebugResponse', 'getMessageMetadataByDebugApi'),
    'get_my_creator_stats': Endpoint('get_my_creator_stats', 'GET', '/v1/creators/me/stats', (), 'CreatorStatsWithDeltaApiDto', 'getMyCreatorStatsApi'),
    'get_my_user_plot_chat_profile': Endpoint('get_my_user_plot_chat_profile', 'GET', '/v1/rooms/:roomId/user-plot-chat-profiles/me', ('roomId', ), 'UserPlotChatProfileWithSelectedApiDto', 'getMyUserPlotChatProfileApi'),
    'get_nutty_user': Endpoint('get_nutty_user', 'GET', '/v1/nutty/user', (), 'NuttyUserApiDto', 'getNuttyUserApi'),
    'get_onboarding_plot': Endpoint('get_onboarding_plot', 'GET', '/v1/plots/onboarding', (), 'ListOnboardingPlotResponse', 'getOnboardingPlotApi'),
    'get_one_day_pass_refund_eligibility': Endpoint('get_one_day_pass_refund_eligibility', 'GET', '/v1/zeta-pass/one-day-pass/refund/eligibility', (), 'OneDayPassRefundEligibilityResponse', 'getOneDayPassRefundEligibilityApi'),
    'get_plot': Endpoint('get_plot', 'GET', '/v1/plots/:plotId', ('plotId', ), 'DetailedPlotApiDto', 'getPlotApi'),
    'get_plot_by_viewer': Endpoint('get_plot_by_viewer', 'GET', '/v1/plots/:plotId/viewer', ('plotId', ), 'DetailedPlotApiDto', 'getPlotByViewerApi'),
    'get_plot_comment_count': Endpoint('get_plot_comment_count', 'GET', '/v1/plots/:plotId/comments/count', ('plotId', ), 'PlotCommentCountResponse', 'getPlotCommentCountApi'),
    'get_plot_comment_setting': Endpoint('get_plot_comment_setting', 'GET', '/v1/creator/plots/:plotId/comment-setting', ('plotId', ), 'PlotCommentSettingResponse', 'getPlotCommentSettingApi'),
    'get_plot_count_by_keyword': Endpoint('get_plot_count_by_keyword', 'GET', '/v1/plots/search/plot-count', (), 'GetPlotCountByKeywordResponse', 'getPlotCountByKeywordApi'),
    'get_plot_draft_first_original_character_profile_image_url': Endpoint('get_plot_draft_first_original_character_profile_image_url', 'GET', '/v2/plots/:plotId/characters/:characterId/images/original/first', ('plotId', 'characterId', ), 'GetOriginalPlotCharacterImageResponse', 'getPlotDraftFirstOriginalCharacterProfileImageUrlApi'),
    'get_plot_draft_first_original_cover_image_url': Endpoint('get_plot_draft_first_original_cover_image_url', 'GET', '/v2/plots/:plotId/images/original/first', ('plotId', ), 'GetOriginalPlotCoverImageResponse', 'getPlotDraftFirstOriginalCoverImageUrlApi'),
    'get_plot_id': Endpoint('get_plot_id', 'GET', '/v1/rooms/:roomId/plot-id', ('roomId', ), 'GetPlotIdResponse', 'getPlotIdApi'),
    'get_plot_like_summary_v2': Endpoint('get_plot_like_summary_v2', 'GET', '/v2/plots/:plotId/likes/summary', ('plotId', ), 'PlotLikeSummaryResponseV2', 'getPlotLikeSummaryV2Api'),
    'get_plot_original_chat_profile_image_url': Endpoint('get_plot_original_chat_profile_image_url', 'GET', '/v2/plots/:plotId/chat-profiles/:chatProfileId/images/original', ('plotId', 'chatProfileId', ), 'GetOriginalPlotChatProfileImageResponse', 'getPlotOriginalChatProfileImageUrlApi'),
    'get_plot_profile_image_generation_job': Endpoint('get_plot_profile_image_generation_job', 'GET', '/v1/plots/profile-image/job/:jobId', ('jobId', ), 'GetPlotProfileImageGenerationJobResponse', 'getPlotProfileImageGenerationJobApi'),
    'get_plot_profile_image_generation_result': Endpoint('get_plot_profile_image_generation_result', 'GET', '/v1/plots/profile-image/:profileImageResultId', ('profileImageResultId', ), 'GetPlotProfileImageGenerationResultResponse', 'getPlotProfileImageGenerationResultApi'),
    'get_plot_profile_image_generation_result_history': Endpoint('get_plot_profile_image_generation_result_history', 'GET', '/v1/plots/profile-image/:plotId/history', ('plotId', ), 'GetPlotProfileImageGenerationResultListResponse', 'getPlotProfileImageGenerationResultHistoryApi'),
    'get_plot_profile_image_generation_styles': Endpoint('get_plot_profile_image_generation_styles', 'GET', '/v1/plots/profile-image/styles', (), 'GetPlotProfileImageGenerationStyleListResponse', 'getPlotProfileImageGenerationStylesApi'),
    'get_plot_profile_image_saved_result_count': Endpoint('get_plot_profile_image_saved_result_count', 'GET', '/v1/plots/saved-profile-image/count', (), 'GetPlotProfileImageGenerationSavedResultCountResponse', 'getPlotProfileImageSavedResultCountApi'),
    'get_plot_profile_image_saved_result_list': Endpoint('get_plot_profile_image_saved_result_list', 'GET', '/v1/plots/saved-profile-image/list', (), 'GetPlotProfileImageGenerationSavedResultListResponse', 'getPlotProfileImageSavedResultListApi'),
    'get_plot_stats': Endpoint('get_plot_stats', 'GET', '/v1/creators/dashboard/plots/:plotId/stats', ('plotId', ), 'CreatorDashboardPlotStatsApiDto', 'getPlotStatsApi'),
    'get_plot_summary': Endpoint('get_plot_summary', 'GET', '/v1/plot-summaries/:plotId', ('plotId', ), 'PlotSummaryApiDto', 'getPlotSummaryApi'),
    'get_pre_release_plot': Endpoint('get_pre_release_plot', 'GET', '/v1/plots/prerelease/recent', (), 'RecentPreReleasePlotResponse', 'getPreReleasePlotApi'),
    'get_predefined_tags': Endpoint('get_predefined_tags', 'GET', '/v1/plots/profile-image/tool/tags', (), 'GetPlotProfileImagePredefinedTagsListResponse', 'getPredefinedTagsApi'),
    'get_preferred_genres_representative_plots': Endpoint('get_preferred_genres_representative_plots', 'GET', '/v1/genres/preferred/representative-plots', (), 'PreferredGenresRepresentativePlotsResponse', 'getPreferredGenresRepresentativePlotsApi'),
    'get_profile': Endpoint('get_profile', 'GET', '/v1/users/me', (), 'UserMeResponse', 'getProfileApi'),
    'get_recommended_keywords': Endpoint('get_recommended_keywords', 'GET', '/v1/plots/search/keywords/recommended', (), 'ListPlotRecommendedKeywordResponse', 'getRecommendedKeywordsApi'),
    'get_recommended_message_quota': Endpoint('get_recommended_message_quota', 'GET', '/v1/recommended-messages/quota', (), 'RecommendedMessageQuotaResponse', 'getRecommendedMessageQuotaApi'),
    'get_recommended_messages': Endpoint('get_recommended_messages', 'GET', '/v1/rooms/:roomId/recommended-messages', ('roomId', ), 'RecommendedMessageHistoryResponse', 'getRecommendedMessagesApi'),
    'get_recommended_placeholder': Endpoint('get_recommended_placeholder', 'GET', '/v1/plots/search/recommended-placeholder', (), 'PlotSearchRecommendedPlaceholderResponse', 'getRecommendedPlaceholderApi'),
    'get_related_keywords': Endpoint('get_related_keywords', 'GET', '/v1/plots/search/related-keywords', (), 'GetRelatedKeywordsResponse', 'getRelatedKeywordsApi'),
    'get_rendered_layout_section': Endpoint('get_rendered_layout_section', 'GET', '/v1/layout-sections/:layoutSectionId', ('layoutSectionId', ), 'GetRenderedLayoutSectionResponse', 'getRenderedLayoutSectionApi'),
    'get_room': Endpoint('get_room', 'GET', '/v1/rooms/:roomId', ('roomId', ), 'RoomApiDto', 'getRoomApi'),
    'get_room_intros_before_selection': Endpoint('get_room_intros_before_selection', 'GET', '/v1/rooms/:roomId/intros/before-selection', ('roomId', ), 'RoomIntrosBeforeSelectionResponse', 'getRoomIntrosBeforeSelectionApi'),
    'get_room_model_setting': Endpoint('get_room_model_setting', 'GET', '/v1/rooms/:roomId/model-setting', ('roomId', ), 'RoomModelSettingApiDto', 'getRoomModelSettingApi'),
    'get_saved_room_status': Endpoint('get_saved_room_status', 'GET', '/v1/rooms/plots/:plotId/saved-room-status', ('plotId', ), 'GetSavedRoomStatusResponse', 'getSavedRoomStatusApi'),
    'get_search_autocomplete': Endpoint('get_search_autocomplete', 'GET', '/v1/plots/search/autocomplete', (), 'ListPlotSearchAutoCompleteResponse', 'getSearchAutocompleteApi'),
    'get_selected_user_chat_profile': Endpoint('get_selected_user_chat_profile', 'GET', '/v1/user-chat-profiles/selected', (), 'UserChatProfileApiDto', 'getSelectedUserChatProfileApi'),
    'get_selected_user_persona': Endpoint('get_selected_user_persona', 'GET', '/v1/plots/:plotId/rooms/:roomId/user-personas/selected', ('plotId', 'roomId', ), 'UserPersonaApiDto', 'getSelectedUserPersonaApi'),
    'get_topic_rankings': Endpoint('get_topic_rankings', 'GET', '/v1/topics/:topicId/plot-rankings', ('topicId', ), 'ListPlotTopicRankingResponse', 'getTopicRankingsApi'),
    'get_topics': Endpoint('get_topics', 'GET', '/v1/topics', (), 'ListPlotTopicResponse', 'getTopicsApi'),
    'get_toss_payment_methods': Endpoint('get_toss_payment_methods', 'GET', '/v1/toss-payments/payment-methods', (), 'TossPaymentMethodsResponse', 'getTossPaymentMethodsApi'),
    'get_user': Endpoint('get_user', 'GET', '/v1/users/:userId', ('userId', ), 'UserApiDto', 'getUserApi'),
    'get_user_chat_profile': Endpoint('get_user_chat_profile', 'GET', '/v1/user-chat-profiles/:id', ('id', ), 'UserChatProfileApiDto', 'getUserChatProfileApi'),
    'get_user_genre_ranking': Endpoint('get_user_genre_ranking', 'GET', '/v1/genres/ranking', (), 'UserGenreRankingResponse', 'getUserGenreRankingApi'),
    'get_user_id_by_username': Endpoint('get_user_id_by_username', 'GET', '/v1/users/get-id-by-username/:username', ('username', ), 'GetUserIdResponse', 'getUserIdByUsernameApi'),
    'get_user_plot_chat_profile': Endpoint('get_user_plot_chat_profile', 'GET', '/v1/rooms/:roomId/user-plot-chat-profiles/:id', ('roomId', 'id', ), 'UserPlotChatProfileApiDto', 'getUserPlotChatProfileApi'),
    'get_username': Endpoint('get_username', 'GET', '/v1/usernames/:username', ('username', ), 'UsernameResponse', 'getUsernameApi'),
    'get_z_labs_first_chat_reward': Endpoint('get_z_labs_first_chat_reward', 'GET', '/v1/zlabs/first-chat-reward', (), None, 'getZLabsFirstChatRewardApi'),
    'get_z_labs_random_popular_plots': Endpoint('get_z_labs_random_popular_plots', 'GET', '/v1/zlabs/popular-plots/random', (), 'ZLabsRandomPopularPlotsResponse', 'getZLabsRandomPopularPlotsApi'),
    'get_z_labs_recent_plays': Endpoint('get_z_labs_recent_plays', 'GET', '/v1/zlabs/recent-plays', (), 'ZLabsRecentPlaysResponse', 'getZLabsRecentPlaysApi'),
    'get_z_labs_related_plots': Endpoint('get_z_labs_related_plots', 'GET', '/v1/zlabs/plots/:plotId/related', ('plotId', ), 'ZLabsPlotSummaryApiDto', 'getZLabsRelatedPlotsApi'),
    'get_zeta_pass_payment_method': Endpoint('get_zeta_pass_payment_method', 'GET', '/v1/zeta-pass/payment-method', (), 'ZetaPassPaymentMethodResponse', 'getZetaPassPaymentMethodApi'),
    'get_zeta_pass_pro_conversion_preview': Endpoint('get_zeta_pass_pro_conversion_preview', 'GET', '/v1/zeta-pass/pro-conversion/preview', (), 'ZetaPassProConversionPreviewResponse', 'getZetaPassProConversionPreviewApi'),
    'get_zeta_pass_pro_conversion_status': Endpoint('get_zeta_pass_pro_conversion_status', 'GET', '/v1/zeta-pass/pro-conversion/status', (), 'ZetaPassProConversionStatusResponse', 'getZetaPassProConversionStatusApi'),
    'get_zeta_pass_promotion_eligibility': Endpoint('get_zeta_pass_promotion_eligibility', 'GET', '/v1/zeta-pass/promotion/eligibility', (), 'ZetaPassPromotionEligibilityResponse', 'getZetaPassPromotionEligibilityApi'),
    'get_zeta_pass_refund_eligibility': Endpoint('get_zeta_pass_refund_eligibility', 'GET', '/v1/zeta-pass/refund/eligibility', (), 'ZetaPassRefundEligibilityResponse', 'getZetaPassRefundEligibilityApi'),
    'get_zeta_pass_subscription': Endpoint('get_zeta_pass_subscription', 'GET', '/v1/zeta-pass/subscription', (), None, 'getZetaPassSubscriptionApi'),
    'invalidate_zeta_pass_cache': Endpoint('invalidate_zeta_pass_cache', 'POST', '/debug/zeta-pass/cache/invalidate', (), None, 'invalidateZetaPassCacheApi'),
    'is_plot_scrapped': Endpoint('is_plot_scrapped', 'GET', '/v1/plots/:plotId/scraps', ('plotId', ), 'IsPlotScrappedResponse', 'isPlotScrappedApi'),
    'issue_token': Endpoint('issue_token', 'POST', '/v1/auth/tokens', (), 'TokenApiDto', 'issueTokenApi'),
    'leave_contest': Endpoint('leave_contest', 'DELETE', '/v1/contest/plots/:plotId', ('plotId', ), None, 'leaveContestApi'),
    'like_plot_comment': Endpoint('like_plot_comment', 'POST', '/v1/plots/:plotId/comments/:commentId/likes', ('plotId', 'commentId', ), None, 'likePlotCommentApi'),
    'like_plot_v2': Endpoint('like_plot_v2', 'PUT', '/v2/plots/:plotId/likes', ('plotId', ), None, 'likePlotV2Api'),
    'list_all_plot_character_images': Endpoint('list_all_plot_character_images', 'GET', '/v2/plots/:plotId/all-character-images', ('plotId', ), 'ListAllPlotCharacterImageResponse', 'listAllPlotCharacterImagesApi'),
    'list_all_plot_character_images_for_preview': Endpoint('list_all_plot_character_images_for_preview', 'GET', '/v2/plots/:plotId/all-character-images/preview', ('plotId', ), 'ListAllPlotCharacterImageResponse', 'listAllPlotCharacterImagesForPreviewApi'),
    'list_announcements': Endpoint('list_announcements', 'GET', '/v1/announcements/', (), 'ListAnnouncementResponse', 'listAnnouncementsApi'),
    'list_auto_payment_settings': Endpoint('list_auto_payment_settings', 'GET', '/v1/coin/auto-payment/settings', (), 'ListAutoPaymentSettingsResponse', 'listAutoPaymentSettingsApi'),
    'list_blocked_hashtag': Endpoint('list_blocked_hashtag', 'GET', '/v1/plots/hashtags/blocks', (), 'ListBlockedHashtagResponse', 'listBlockedHashtagApi'),
    'list_blocked_plot': Endpoint('list_blocked_plot', 'GET', '/v1/plots/blocks', (), 'ListBlockedPlotResponse', 'listBlockedPlotApi'),
    'list_blocked_user': Endpoint('list_blocked_user', 'GET', '/v1/users/blocks', (), 'ListBlockedUserResponse', 'listBlockedUserApi'),
    'list_candidate': Endpoint('list_candidate', 'GET', '/v1/rooms/:roomId/messages/:messageId/candidates', ('roomId', 'messageId', ), 'ListCandidateResponse', 'listCandidateApi'),
    'list_chat_message_report_categories': Endpoint('list_chat_message_report_categories', 'GET', '/v1/chat-message-report-categories', (), 'ListChatMessageReportCategoryResponse', 'listChatMessageReportCategoriesApi'),
    'list_chat_model_config': Endpoint('list_chat_model_config', 'GET', '/v1/chat-model-configs', (), 'ListChatModelConfigResponse', 'listChatModelConfigApi'),
    'list_coin_expirations': Endpoint('list_coin_expirations', 'GET', '/v1/coin/expirations', (), 'ListCoinExpirationResponse', 'listCoinExpirationsApi'),
    'list_coin_products': Endpoint('list_coin_products', 'GET', '/v1/coin-products', (), 'ListCoinProductsResponse', 'listCoinProductsApi'),
    'list_coin_transactions': Endpoint('list_coin_transactions', 'GET', '/v1/coin/transactions', (), 'ListCoinTransactionResponse', 'listCoinTransactionsApi'),
    'list_contest_plots': Endpoint('list_contest_plots', 'GET', '/v1/contest/plots', (), 'PagePlotResponse', 'listContestPlotsApi'),
    'list_creator_plot_comments': Endpoint('list_creator_plot_comments', 'GET', '/v1/creator/comments', (), 'PageCreatorCommentResponse', 'listCreatorPlotCommentsApi'),
    'list_dev_server': Endpoint('list_dev_server', 'GET', '/debug/dev-server', (), 'ListDevServerResponse', 'listDevServerApi'),
    'list_follower': Endpoint('list_follower', 'GET', '/v1/creators/:creatorId/followers', ('creatorId', ), 'ListFollowerResponse', 'listFollowerApi'),
    'list_following_creator': Endpoint('list_following_creator', 'GET', '/v1/creators/:creatorId/followings', ('creatorId', ), 'ListFollowingCreatorResponse', 'listFollowingCreatorApi'),
    'list_hashtag_topic_plots': Endpoint('list_hashtag_topic_plots', 'GET', '/v1/hashtag-topics/:hashtag/plots', ('hashtag', ), 'ListHashtagTopicPlotsResponse', 'listHashtagTopicPlotsApi'),
    'list_hashtag_topics': Endpoint('list_hashtag_topics', 'GET', '/v1/hashtag-topics', (), 'ListHashtagTopicResponse', 'listHashtagTopicsApi'),
    'list_liked_plots_v2': Endpoint('list_liked_plots_v2', 'GET', '/v2/plots/liked', (), 'ListLikedPlotResponseV2', 'listLikedPlotsV2Api'),
    'list_lorebooks_for_creator': Endpoint('list_lorebooks_for_creator', 'GET', '/v1/lorebooks/creator', (), 'ListLorebooksForCreatorResponse', 'listLorebooksForCreatorApi'),
    'list_message_bookmark': Endpoint('list_message_bookmark', 'GET', '/v1/rooms/:roomId/bookmarks', ('roomId', ), 'ListMessageBookmarksResponse', 'listMessageBookmarkApi'),
    'list_messages': Endpoint('list_messages', 'GET', '/v1/rooms/:roomId/messages', ('roomId', ), 'ListMessageResponse', 'listMessagesApi'),
    'list_my_account_blocks': Endpoint('list_my_account_blocks', 'GET', '/v1/users/me/account-blocks', (), 'ListMyAccountBlocksResponse', 'listMyAccountBlocksApi'),
    'list_my_contest_entries': Endpoint('list_my_contest_entries', 'GET', '/v1/contest/entries', (), 'ContestEntryApiDto', 'listMyContestEntriesApi'),
    'list_my_plots_by_lorebook_id': Endpoint('list_my_plots_by_lorebook_id', 'GET', '/v1/lorebooks/:lorebookId/my-plots', ('lorebookId', ), 'ListMyLorebookPlotsResponse', 'listMyPlotsByLorebookIdApi'),
    'list_my_visible_lorebooks': Endpoint('list_my_visible_lorebooks', 'GET', '/v1/lorebooks', (), 'ListLorebooksResponse', 'listMyVisibleLorebooksApi'),
    'list_notifications': Endpoint('list_notifications', 'GET', '/v1/notifications', (), 'ListNotificationsResponse', 'listNotificationsApi'),
    'list_plot': Endpoint('list_plot', 'GET', '/v1/plots', (), 'PagePlotResponse', 'listPlotApi'),
    'list_plot_character_profile_image': Endpoint('list_plot_character_profile_image', 'GET', '/v2/plots/:plotId/characters/:characterId/images', ('plotId', 'characterId', ), 'ListPlotCharacterImageResponse', 'listPlotCharacterProfileImageApi'),
    'list_plot_character_profile_image_for_creator': Endpoint('list_plot_character_profile_image_for_creator', 'GET', '/v2/plots/:plotId/characters/:characterId/images/creator', ('plotId', 'characterId', ), 'ListPlotCharacterImageResponse', 'listPlotCharacterProfileImageForCreatorApi'),
    'list_plot_comment_activities': Endpoint('list_plot_comment_activities', 'GET', '/v1/plot-comment-activities', (), 'ListPlotCommentActivityResponse', 'listPlotCommentActivitiesApi'),
    'list_plot_comment_replies': Endpoint('list_plot_comment_replies', 'GET', '/v1/plots/:plotId/comments/:commentId/replies', ('plotId', 'commentId', ), 'PagePlotCommentResponse', 'listPlotCommentRepliesApi'),
    'list_plot_comments': Endpoint('list_plot_comments', 'GET', '/v1/plots/:plotId/comments', ('plotId', ), 'PagePlotCommentResponse', 'listPlotCommentsApi'),
    'list_plot_cover_image': Endpoint('list_plot_cover_image', 'GET', '/v2/plots/:plotId/images', ('plotId', ), 'ListPlotCoverImageResponse', 'listPlotCoverImageApi'),
    'list_plot_cover_image_for_creator': Endpoint('list_plot_cover_image_for_creator', 'GET', '/v2/plots/:plotId/images/creator', ('plotId', ), 'ListPlotCoverImageResponse', 'listPlotCoverImageForCreatorApi'),
    'list_plot_cover_image_for_preview': Endpoint('list_plot_cover_image_for_preview', 'GET', '/v2/plots/:plotId/images/creator/preview', ('plotId', ), 'ListPlotCoverImageForPreviewResponse', 'listPlotCoverImageForPreviewApi'),
    'list_plot_for_creator': Endpoint('list_plot_for_creator', 'GET', '/v1/plots/creator', (), 'PagePlotForCreatorResponse', 'listPlotForCreatorApi'),
    'list_plot_like_users_v2': Endpoint('list_plot_like_users_v2', 'GET', '/v2/plots/:plotId/likes', ('plotId', ), 'ListPlotLikeUsersResponseV2', 'listPlotLikeUsersV2Api'),
    'list_plot_ranking': Endpoint('list_plot_ranking', 'GET', '/v1/plots/ranking', (), 'ListPlotRankingResponse', 'listPlotRankingApi'),
    'list_plot_snapshot_images': Endpoint('list_plot_snapshot_images', 'GET', '/v1/plots/:plotId/snapshot-images', ('plotId', ), 'ListPlotSnapshotImageResponse', 'listPlotSnapshotImagesApi'),
    'list_plots_by_lorebook_id': Endpoint('list_plots_by_lorebook_id', 'GET', '/v1/lorebooks/:lorebookId/plots', ('lorebookId', ), 'PageLorebookAttachedPlotResponse', 'listPlotsByLorebookIdApi'),
    'list_plots_in_pool': Endpoint('list_plots_in_pool', 'GET', '/v1/plot-pools/:poolId/plots', ('poolId', ), 'PagePlotResponse', 'listPlotsInPoolApi'),
    'list_popups': Endpoint('list_popups', 'GET', '/v1/popups', (), 'ListPopupResponse', 'listPopupsApi'),
    'list_products': Endpoint('list_products', 'GET', '/v1/open-stores/:storeType/products', ('storeType', ), 'ListProductsResponse', 'listProductsApi'),
    'list_random_recently_created_plot': Endpoint('list_random_recently_created_plot', 'GET', '/v1/plots/random-recently-created', (), 'ListPlotResponse', 'listRandomRecentlyCreatedPlotApi'),
    'list_rooms': Endpoint('list_rooms', 'GET', '/v1/rooms', (), 'ListRoomsResponse', 'listRoomsApi'),
    'list_rooms_v2': Endpoint('list_rooms_v2', 'GET', '/v2/rooms', (), 'ListRoomsResponseV2', 'listRoomsV2Api'),
    'list_saved_rooms': Endpoint('list_saved_rooms', 'GET', '/v1/rooms/saved', (), 'ListSavedRoomsResponse', 'listSavedRoomsApi'),
    'list_similar_plots': Endpoint('list_similar_plots', 'GET', '/v1/plots/:plotId/similar-plots', ('plotId', ), 'ListSimilarPlotsResponse', 'listSimilarPlotsApi'),
    'list_user_chat_profile': Endpoint('list_user_chat_profile', 'GET', '/v1/user-chat-profiles', (), 'UserChatProfileListResponse', 'listUserChatProfileApi'),
    'load_saved_room': Endpoint('load_saved_room', 'POST', '/v1/rooms/:roomId/load', ('roomId', ), 'RoomApiDto', 'loadSavedRoomApi'),
    'logout': Endpoint('logout', 'POST', '/v1/users/logout', (), None, 'logoutApi'),
    'migrate_chat': Endpoint('migrate_chat', 'POST', '/v1/nutty/migrate', (), None, 'migrateChatApi'),
    'option': Endpoint('option', 'POST', '/v1/rooms/:roomId/options/stream', ('roomId', ), None, 'optionApi'),
    'option_regen': Endpoint('option_regen', 'POST', '/v1/rooms/:roomId/options/stream/more', ('roomId', ), None, 'optionRegenApi'),
    'page_plot_scrapped': Endpoint('page_plot_scrapped', 'GET', '/v1/plots/scrapped', (), 'PagePlotScrappedResponse', 'pagePlotScrappedApi'),
    'patch_auto_payment_setting': Endpoint('patch_auto_payment_setting', 'PATCH', '/v1/coin/auto-payment/settings', (), None, 'patchAutoPaymentSettingApi'),
    'patch_my_user_plot_chat_profile': Endpoint('patch_my_user_plot_chat_profile', 'PATCH', '/v1/rooms/:roomId/user-plot-chat-profiles/me', ('roomId', ), 'UserPlotChatProfileApiDto', 'patchMyUserPlotChatProfileApi'),
    'patch_plot_draft_by_creator': Endpoint('patch_plot_draft_by_creator', 'PATCH', '/v1/plots/:plotId', ('plotId', ), 'PlotForCreatorApiDto', 'patchPlotDraftByCreatorApi'),
    'patch_user_chat_profile': Endpoint('patch_user_chat_profile', 'PATCH', '/v1/user-chat-profiles/:id', ('id', ), 'UserChatProfileApiDto', 'patchUserChatProfileApi'),
    'patch_user_profile': Endpoint('patch_user_profile', 'PATCH', '/v1/users/me', (), None, 'patchUserProfileApi'),
    'pin_plot_comment': Endpoint('pin_plot_comment', 'PUT', '/v1/creator/plots/:plotId/comments/:commentId/pin', ('plotId', 'commentId', ), None, 'pinPlotCommentApi'),
    'pin_room': Endpoint('pin_room', 'POST', '/v1/rooms/:roomId/pin', ('roomId', ), None, 'pinRoomApi'),
    'purchase_bulk': Endpoint('purchase_bulk', 'PUT', '/v1/open-stores/:storeType/purchases', ('storeType', ), None, 'purchaseBulkApi'),
    'purchase_coin_product': Endpoint('purchase_coin_product', 'POST', '/v1/coin-products/:productId/purchases', ('productId', ), None, 'purchaseCoinProductApi'),
    'purchase_product': Endpoint('purchase_product', 'POST', '/v1/open-stores/:storeType/products/:productId/purchases', ('storeType', 'productId', ), None, 'purchaseProductApi'),
    'purchase_recommended_messages': Endpoint('purchase_recommended_messages', 'POST', '/v1/rooms/:roomId/recommended-messages/purchase', ('roomId', ), None, 'purchaseRecommendedMessagesApi'),
    'purchase_zeta_pass_one_day_pass_via_app_store': Endpoint('purchase_zeta_pass_one_day_pass_via_app_store', 'POST', '/v1/zeta-pass/one-day-pass/purchase/app-store', (), 'ZetaPassOneDayPassResponse', 'purchaseZetaPassOneDayPassViaAppStoreApi'),
    'purchase_zeta_pass_one_day_pass_via_play_store': Endpoint('purchase_zeta_pass_one_day_pass_via_play_store', 'POST', '/v1/zeta-pass/one-day-pass/purchase/play-store', (), 'ZetaPassOneDayPassResponse', 'purchaseZetaPassOneDayPassViaPlayStoreApi'),
    'purge_rooms': Endpoint('purge_rooms', 'POST', '/v1/rooms/purge', (), None, 'purgeRoomsApi'),
    'rate_chat_snapshot_image': Endpoint('rate_chat_snapshot_image', 'POST', '/v1/rooms/:roomId/messages/:messageId/candidates/:candidateId/snapshot-images/:snapshotImageId/ratings', ('roomId', 'messageId', 'candidateId', 'snapshotImageId', ), None, 'rateChatSnapshotImageApi'),
    'rate_generated_plot_character_image': Endpoint('rate_generated_plot_character_image', 'POST', '/v2/plots/:plotId/characters/:characterId/images/ratings', ('plotId', 'characterId', ), None, 'rateGeneratedPlotCharacterImageApi'),
    'rate_generated_plot_cover_image': Endpoint('rate_generated_plot_cover_image', 'POST', '/v2/plots/:plotId/images/ratings', ('plotId', ), None, 'rateGeneratedPlotCoverImageApi'),
    'reactivate_zeta_pass': Endpoint('reactivate_zeta_pass', 'POST', '/v1/zeta-pass/reactivate', (), 'ZetaPassSubscriptionResponse', 'reactivateZetaPassApi'),
    'regen': Endpoint('regen', 'POST', '/v1/rooms/:roomId/messages/:messageId/candidates/stream', ('roomId', 'messageId', ), None, 'regenApi'),
    'register_plot_profile_image_generation_job': Endpoint('register_plot_profile_image_generation_job', 'POST', '/v1/plots/profile-image/:plotId/job/register', ('plotId', ), 'RegisterPlotProfileImageGenerationJobResponse', 'registerPlotProfileImageGenerationJobApi'),
    'report_character_profile_image_generation_result': Endpoint('report_character_profile_image_generation_result', 'POST', '/v1/plots/profile-image/result/:profileImageResultId/report', ('profileImageResultId', ), None, 'reportCharacterProfileImageGenerationResultApi'),
    'report_chat_snapshot_image': Endpoint('report_chat_snapshot_image', 'POST', '/v1/rooms/:roomId/messages/:messageId/candidates/:candidateId/snapshot-images/:snapshotImageId/reports', ('roomId', 'messageId', 'candidateId', 'snapshotImageId', ), None, 'reportChatSnapshotImageApi'),
    'report_plot_comment': Endpoint('report_plot_comment', 'POST', '/v1/plots/:plotId/comments/:commentId/reports', ('plotId', 'commentId', ), 'ReportPlotCommentResponse', 'reportPlotCommentApi'),
    'report_user': Endpoint('report_user', 'POST', '/v1/users/:userId/report', ('userId', ), None, 'reportUserApi'),
    'request_creator_assistant_brief_plot_job': Endpoint('request_creator_assistant_brief_plot_job', 'POST', '/v2/creator-assistant/generate-plot', (), 'CreatorAssistantSubmitPlotJobResponse', 'requestCreatorAssistantBriefPlotJobApi'),
    'request_daily_quiz': Endpoint('request_daily_quiz', 'GET', '/v1/daily-quizzes', (), None, 'requestDailyQuizApi'),
    'request_nice_additional_auth': Endpoint('request_nice_additional_auth', 'POST', '/v2/additional-auth/nice', (), 'RequestAdditionalAuthResponse', 'requestNiceAdditionalAuthApi'),
    'request_one_day_pass_refund': Endpoint('request_one_day_pass_refund', 'POST', '/v1/zeta-pass/one-day-pass/refund', (), 'OneDayPassRefundResultResponse', 'requestOneDayPassRefundApi'),
    'request_toss_payments': Endpoint('request_toss_payments', 'POST', '/v1/toss-payments/orders', (), 'TossPaymentsResponse', 'requestTossPaymentsApi'),
    'request_zeta_pass_one_day_pass_web_order': Endpoint('request_zeta_pass_one_day_pass_web_order', 'POST', '/v1/zeta-pass/one-day-pass/purchase/web/orders', (), 'ZetaPassOneDayPassOrderResponse', 'requestZetaPassOneDayPassWebOrderApi'),
    'request_zeta_pass_refund': Endpoint('request_zeta_pass_refund', 'POST', '/v1/zeta-pass/refund', (), 'ZetaPassRefundResultResponse', 'requestZetaPassRefundApi'),
    'request_zeta_pass_renewal_reminder': Endpoint('request_zeta_pass_renewal_reminder', 'POST', '/v1/zeta-pass/renewal-reminder', (), 'ZetaPassSubscriptionResponse', 'requestZetaPassRenewalReminderApi'),
    'revert_zeta_pass_promotion_consent_to_pending': Endpoint('revert_zeta_pass_promotion_consent_to_pending', 'POST', '/debug/zeta-pass/revert-promotion-consent', (), None, 'revertZetaPassPromotionConsentToPendingApi'),
    'reward_daily': Endpoint('reward_daily', 'POST', '/v1/coin/daily-rewards', (), 'CoinDailyRewardResponse', 'rewardDailyApi'),
    'run_zeta_pass_web_lifecycle': Endpoint('run_zeta_pass_web_lifecycle', 'POST', '/debug/zeta-pass/web-lifecycle/run', (), None, 'runZetaPassWebLifecycleApi'),
    'scrap_plot': Endpoint('scrap_plot', 'PUT', '/v1/plots/:plotId/scraps', ('plotId', ), None, 'scrapPlotApi'),
    'search_lorebooks': Endpoint('search_lorebooks', 'GET', '/v1/lorebooks/search', (), 'LorebookSearchResponse', 'searchLorebooksApi'),
    'search_plot': Endpoint('search_plot', 'GET', '/v1/plots/search', (), 'PagePlotSearchResponse', 'searchPlotApi'),
    'search_z_labs_plots': Endpoint('search_z_labs_plots', 'GET', '/v1/zlabs/plots/search', (), 'ZLabsPlotListResponse', 'searchZLabsPlotsApi'),
    'select_user_chat_profile': Endpoint('select_user_chat_profile', 'PUT', '/v1/user-chat-profiles/:id/selected', ('id', ), None, 'selectUserChatProfileApi'),
    'select_user_plot_chat_profile': Endpoint('select_user_plot_chat_profile', 'PUT', '/v1/rooms/:roomId/user-plot-chat-profiles/:id/selected', ('roomId', 'id', ), None, 'selectUserPlotChatProfileApi'),
    'send_multiple_recommend_message': Endpoint('send_multiple_recommend_message', 'POST', '/v1/rooms/:roomId/recommended-messages/multiple', ('roomId', ), 'RecommendedMessageResponse', 'sendMultipleRecommendMessageApi'),
    'send_sms': Endpoint('send_sms', 'POST', '/v1/nutty/sms', (), None, 'sendSmsApi'),
    'set_default_user_chat_profile': Endpoint('set_default_user_chat_profile', 'PUT', '/v1/user-chat-profiles/:id/default', ('id', ), None, 'setDefaultUserChatProfileApi'),
    'set_preferred_genres': Endpoint('set_preferred_genres', 'PUT', '/v1/users/me/preferred-genres', (), None, 'setPreferredGenresApi'),
    'should_warn_on_withdrawal': Endpoint('should_warn_on_withdrawal', 'GET', '/v1/users/me/should-warn-on-withdrawal', (), 'ShouldWarnOnWithdrawalResponse', 'shouldWarnOnWithdrawalApi'),
    'stream_dev_server_logs': Endpoint('stream_dev_server_logs', 'GET', '/debug/dev-server/:serverName/logs', ('serverName', ), 'ServerSentEventString', 'streamDevServerLogsApi'),
    'submit_candidate_feedback': Endpoint('submit_candidate_feedback', 'POST', '/v1/rooms/:roomId/messages/:messageId/candidates/:candidateId/feedback', ('roomId', 'messageId', 'candidateId', ), None, 'submitCandidateFeedbackApi'),
    'submit_contest_application': Endpoint('submit_contest_application', 'POST', '/v1/contest/entries/:plotId/application', ('plotId', ), None, 'submitContestApplicationApi'),
    'submit_quiz_selection': Endpoint('submit_quiz_selection', 'POST', '/v1/daily-quizzes/:quizId/selection', ('quizId', ), None, 'submitQuizSelectionApi'),
    'subscribe_zeta_pass_via_app_store': Endpoint('subscribe_zeta_pass_via_app_store', 'POST', '/v1/zeta-pass/subscribe/app-store', (), 'ZetaPassSubscriptionResponse', 'subscribeZetaPassViaAppStoreApi'),
    'subscribe_zeta_pass_via_brandpay': Endpoint('subscribe_zeta_pass_via_brandpay', 'POST', '/v1/zeta-pass/subscribe/brandpay', (), 'ZetaPassSubscriptionResponse', 'subscribeZetaPassViaBrandpayApi'),
    'subscribe_zeta_pass_via_play_store': Endpoint('subscribe_zeta_pass_via_play_store', 'POST', '/v1/zeta-pass/subscribe/play-store', (), 'ZetaPassSubscriptionResponse', 'subscribeZetaPassViaPlayStoreApi'),
    'test_keyword': Endpoint('test_keyword', 'POST', '/v1/keywords/test', (), 'TestKeywordResponse', 'testKeywordApi'),
    'translate_prompt_into_english': Endpoint('translate_prompt_into_english', 'POST', '/v1/plots/profile-image/tool/translate', (), 'GetPlotProfileImagePromptTranslationResponse', 'translatePromptIntoEnglishApi'),
    'unblock_hashtag': Endpoint('unblock_hashtag', 'DELETE', '/v1/plots/hashtags/blocks', (), None, 'unblockHashtagApi'),
    'unblock_plot': Endpoint('unblock_plot', 'DELETE', '/v1/plots/blocks', (), None, 'unblockPlotApi'),
    'unblock_user': Endpoint('unblock_user', 'DELETE', '/v1/users/blocks', (), None, 'unblockUserApi'),
    'unfollow_creator': Endpoint('unfollow_creator', 'DELETE', '/v1/creators/:creatorId/follow', ('creatorId', ), None, 'unfollowCreatorApi'),
    'unlike_plot_comment': Endpoint('unlike_plot_comment', 'DELETE', '/v1/plots/:plotId/comments/:commentId/likes', ('plotId', 'commentId', ), None, 'unlikePlotCommentApi'),
    'unlike_plot_v2': Endpoint('unlike_plot_v2', 'DELETE', '/v2/plots/:plotId/likes', ('plotId', ), None, 'unlikePlotV2Api'),
    'unpin_plot_comment': Endpoint('unpin_plot_comment', 'DELETE', '/v1/creator/plots/:plotId/comments/:commentId/pin', ('plotId', 'commentId', ), None, 'unpinPlotCommentApi'),
    'unpin_room': Endpoint('unpin_room', 'DELETE', '/v1/rooms/:roomId/pin', ('roomId', ), None, 'unpinRoomApi'),
    'unscrap_plot': Endpoint('unscrap_plot', 'DELETE', '/v1/plots/:plotId/scraps', ('plotId', ), None, 'unscrapPlotApi'),
    'update_app_push_setting': Endpoint('update_app_push_setting', 'PUT', '/v1/app-push/settings/:pushType', ('pushType', ), None, 'updateAppPushSettingApi'),
    'update_candidate': Endpoint('update_candidate', 'PUT', '/v1/rooms/:roomId/messages/:messageId/candidates/:candidateId', ('roomId', 'messageId', 'candidateId', ), 'UpdateCandidateResponse', 'updateCandidateApi'),
    'update_cyoa_setting': Endpoint('update_cyoa_setting', 'PUT', '/v1/rooms/:roomId/settings/cyoa', ('roomId', ), 'RoomCyoaSettingApiDto', 'updateCyoaSettingApi'),
    'update_following_creator_notification_enabled': Endpoint('update_following_creator_notification_enabled', 'POST', '/v1/creators/:creatorId/follow/notification', ('creatorId', ), None, 'updateFollowingCreatorNotificationEnabledApi'),
    'update_info_box_setting': Endpoint('update_info_box_setting', 'PUT', '/v1/rooms/:roomId/settings/info-box', ('roomId', ), 'RoomInfoBoxSettingApiDto', 'updateInfoBoxSettingApi'),
    'update_lorebook': Endpoint('update_lorebook', 'PUT', '/v1/lorebooks/:id', ('id', ), 'LorebookApiDto', 'updateLorebookApi'),
    'update_message': Endpoint('update_message', 'PUT', '/v1/rooms/:roomId/messages/:messageId', ('roomId', 'messageId', ), 'PutMessageResponse', 'updateMessageApi'),
    'update_message_bookmark': Endpoint('update_message_bookmark', 'PUT', '/v1/rooms/:roomId/bookmarks/:bookmarkId', ('roomId', 'bookmarkId', ), 'MessageBookmarkApiDto', 'updateMessageBookmarkApi'),
    'update_plot_comment': Endpoint('update_plot_comment', 'PATCH', '/v1/plots/:plotId/comments/:commentId', ('plotId', 'commentId', ), 'CreatePlotCommentResponse', 'updatePlotCommentApi'),
    'update_plot_comment_setting': Endpoint('update_plot_comment_setting', 'PATCH', '/v1/creator/plots/:plotId/comment-setting', ('plotId', ), 'PlotCommentSettingResponse', 'updatePlotCommentSettingApi'),
    'update_plot_comment_setting_for_all': Endpoint('update_plot_comment_setting_for_all', 'PATCH', '/v1/creator/comment-setting', (), 'PlotCommentSettingResponse', 'updatePlotCommentSettingForAllApi'),
    'update_plot_draft_by_creator': Endpoint('update_plot_draft_by_creator', 'PUT', '/v1/plots/:plotId', ('plotId', ), 'PlotForCreatorApiDto', 'updatePlotDraftByCreatorApi'),
    'update_plot_intro_image_caption': Endpoint('update_plot_intro_image_caption', 'PUT', '/v1/plots/:plotId/intro-images/caption', ('plotId', ), None, 'updatePlotIntroImageCaptionApi'),
    'update_plot_is_private': Endpoint('update_plot_is_private', 'PATCH', '/v1/plots/:plotId/private', ('plotId', ), 'PlotForCreatorApiDto', 'updatePlotIsPrivateApi'),
    'update_plot_status_by_creator': Endpoint('update_plot_status_by_creator', 'PATCH', '/v1/plots/:plotId/status', ('plotId', ), 'PlotForCreatorApiDto', 'updatePlotStatusByCreatorApi'),
    'update_plot_unlimited': Endpoint('update_plot_unlimited', 'PUT', '/v1/plots/:plotId/unlimited', ('plotId', ), None, 'updatePlotUnlimitedApi'),
    'update_room': Endpoint('update_room', 'PUT', '/v1/rooms/:roomId', ('roomId', ), None, 'updateRoomApi'),
    'update_room_model_setting': Endpoint('update_room_model_setting', 'PUT', '/v1/rooms/:roomId/model-setting', ('roomId', ), 'RoomModelSettingApiDto', 'updateRoomModelSettingApi'),
    'update_zeta_pass_start_at': Endpoint('update_zeta_pass_start_at', 'POST', '/debug/zeta-pass/start-at', (), None, 'updateZetaPassStartAtApi'),
    'update_zeta_pass_subscribed_until': Endpoint('update_zeta_pass_subscribed_until', 'POST', '/debug/zeta-pass/subscribed-until', (), None, 'updateZetaPassSubscribedUntilApi'),
    'validate_nice_additional_auth': Endpoint('validate_nice_additional_auth', 'GET', '/v2/additional-auth/nice/validate', (), None, 'validateNiceAdditionalAuthApi'),
    'verify_sms_code': Endpoint('verify_sms_code', 'POST', '/v1/nutty/sms/verify', (), None, 'verifySmsCodeApi'),
    'verify_token': Endpoint('verify_token', 'POST', '/v1/nutty/token/verify', (), None, 'verifyTokenApi'),
}

"""エンドポイント名 -> Endpoint。名前は JS の `xxxApi` を snake_case 化したもの。"""
